### ISSUE TITLE
Feat: docker version

### ISSUE THREAD

**Issue by berntpopp** [scholl-lab/variantcentrifuge#53]

**Comment by berntpopp** [comment]
## Implementation Plan for Docker Support

I've analyzed the project structure and developed a comprehensive plan for adding Docker support to VariantCentrifuge.

### Overview
Create Docker images that package VariantCentrifuge with all bioinformatics dependencies, providing a consistent runtime environment across platforms.

### Implementation Architecture

#### 1. **Multi-Stage Dockerfile**

Create `Dockerfile` in project root:
```dockerfile
# Stage 1: Base bioinformatics tools
FROM condaforge/mambaforge:latest AS biotools

# Install bioinformatics tools via mamba
RUN mamba install -y -c bioconda -c conda-forge \
    bcftools=1.21 \
    bedtools=2.31.1 \
    snpeff=5.2 \
    snpsift=5.2 \
    && mamba clean -afy

# Stage 2: Python dependencies
FROM biotools AS python-deps

# Install Python and dependencies
RUN mamba install -y -c conda-forge \
    python=3.12 \
    pandas=2.2.3 \
    scipy=1.14.1 \
    statsmodels=0.14.4 \
    numpy \
    jinja2 \
    openpyxl=3.1.5 \
    && mamba clean -afy

# Install additional Python packages via pip
RUN pip install --no-cache-dir intervaltree

# Stage 3: Final application image
FROM python-deps AS production

# Set working directory
WORKDIR /app

# Copy application code
COPY . /app/

# Install variantcentrifuge
RUN pip install --no-cache-dir -e .

# Create directories for data
RUN mkdir -p /data /output /references

# Set environment variables
ENV PATH="/opt/conda/bin:$PATH"
ENV PYTHONUNBUFFERED=1

# Default command
ENTRYPOINT ["variantcentrifuge"]
CMD ["--help"]
```

#### 2. **Development Dockerfile**

Create `Dockerfile.dev`:
```dockerfile
FROM variantcentrifuge:base AS development

# Install development tools
RUN mamba install -y -c conda-forge \
    black \
    flake8 \
    pre-commit \
    isort \
    pytest \
    pytest-cov \
    pytest-mock \
    ipython \
    && mamba clean -afy

# Install in editable mode
WORKDIR /workspace
CMD ["/bin/bash"]
```

#### 3. **Docker Compose Configuration**

Create `docker-compose.yml`:
```yaml
version: '3.8'

services:
  variantcentrifuge:
    build:
      context: .
      dockerfile: Dockerfile
    image: variantcentrifuge:latest
    volumes:
      - ./data:/data
      - ./output:/output
      - ./references:/references
    environment:
      - THREADS=4
    command: >
      --vcf-file /data/input.vcf
      --gene-file /data/genes.txt
      --output-file /output/results.tsv

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: variantcentrifuge:dev
    volumes:
      - .:/workspace
      - ./data:/data
      - ./output:/output
    environment:
      - THREADS=4
    stdin_open: true
    tty: true
```

#### 4. **Lightweight Alpine-based Image** (Alternative)

Create `Dockerfile.alpine`:
```dockerfile
FROM alpine:3.19 AS builder

# Install build dependencies
RUN apk add --no-cache \
    python3 \
    py3-pip \
    gcc \
    musl-dev \
    python3-dev \
    bash

# Install bioinformatics tools
RUN apk add --no-cache \
    bcftools \
    bedtools \
    openjdk11-jre

# Download and install SnpEff/SnpSift
RUN wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip \
    && unzip snpEff_latest_core.zip -d /opt/ \
    && rm snpEff_latest_core.zip

FROM alpine:3.19

# Install runtime dependencies
RUN apk add --no-cache \
    python3 \
    bash \
    bcftools \
    bedtools \
    openjdk11-jre

# Copy SnpEff/SnpSift
COPY --from=builder /opt/snpEff /opt/snpEff

# Install Python packages
COPY requirements.txt /tmp/
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

# Copy application
COPY . /app/
WORKDIR /app
RUN pip3 install --no-cache-dir .

# Create snpEff/SnpSift wrapper scripts
RUN echo '#\!/bin/bash\njava -jar /opt/snpEff/snpEff.jar "$@"' > /usr/local/bin/snpEff && \
    echo '#\!/bin/bash\njava -jar /opt/snpEff/SnpSift.jar "$@"' > /usr/local/bin/SnpSift && \
    chmod +x /usr/local/bin/snpEff /usr/local/bin/SnpSift

ENTRYPOINT ["variantcentrifuge"]
```

#### 5. **Helper Scripts**

Create `scripts/docker-run.sh`:
```bash
#\!/bin/bash
# Wrapper script for running variantcentrifuge in Docker

docker run --rm \
    -v "$(pwd)/data:/data" \
    -v "$(pwd)/output:/output" \
    -v "$(pwd)/references:/references" \
    variantcentrifuge:latest "$@"
```

#### 6. **GitHub Actions for Docker Builds**

Create `.github/workflows/docker.yml`:
```yaml
name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags:  < /dev/null | 
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name \!= 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

#### 7. **Documentation**

Create `docs/docker.md`:
```markdown
# Docker Usage Guide

## Quick Start

Pull and run the latest image:
```bash
docker pull ghcr.io/scholl-lab/variantcentrifuge:latest

docker run --rm \
  -v $(pwd)/data:/data \
  -v $(pwd)/output:/output \
  ghcr.io/scholl-lab/variantcentrifuge:latest \
  --vcf-file /data/input.vcf \
  --gene-file /data/genes.txt \
  --output-file /output/results.tsv
```

## Building Locally

```bash
# Build production image
docker build -t variantcentrifuge:latest .

# Build development image
docker build -f Dockerfile.dev -t variantcentrifuge:dev .
```

## Using Docker Compose

```bash
# Run analysis
docker-compose run variantcentrifuge

# Start development environment
docker-compose run dev
```

## Volume Mounts

- `/data`: Input files (VCF, gene lists, etc.)
- `/output`: Analysis results
- `/references`: Reference files (optional)
```

### Benefits

1. **Consistent Environment**: Same versions across all platforms
2. **No Installation Hassles**: All dependencies included
3. **Reproducibility**: Tagged versions for exact reproduction
4. **CI/CD Integration**: Automated builds and testing
5. **Multiple Variants**: Production, development, and lightweight images
6. **Easy Distribution**: Via GitHub Container Registry

### Testing Strategy

1. Build images in CI for all PRs
2. Test basic functionality: `--help`, `--version`
3. Run integration tests inside container
4. Multi-platform builds (linux/amd64, linux/arm64)
5. Security scanning with Trivy/Snyk

### Future Enhancements

1. **Biocontainers Integration**: Submit to biocontainers registry
2. **Singularity/Apptainer**: HPC-friendly container format
3. **GPU Support**: For future ML-based features
4. **Multi-architecture**: ARM64 support for Apple Silicon
5. **Minimal Images**: Distroless or scratch-based images

This approach provides flexible Docker support while maintaining ease of use and broad compatibility.
